// DO NOT EDIT THIS FILE
// This file is automatically generated when new ApplicationConfigs are serialized
// look in /shmaplib/appdata.py at regenerate_site_apps_js()

var sitedata_apps = [
    {
        name: "Adobe Lightroom",
        data: {
            "v5.4": {
                "mac": "adobe-lightroom_v5.4_mac.json",
                "windows": "adobe-lightroom_v5.4_windows.json",
            },
        }
    },
    {
        name: "Adobe Photoshop",
        data: {
            "v14.2": {
                "mac": "adobe-photoshop_v14.2_mac.json",
                "windows": "adobe-photoshop_v14.2_windows.json",
            },
        }
    },
    {
        name: "Audodesk 3dsMax",
        data: {
            "2015": {
                "windows": "audodesk-3dsmax_2015_windows.json",
            },
        }
    },
    {
        name: "Audodesk Maya",
        data: {
            "2014": {
                "mac": "audodesk-maya_2014_mac.json",
                "windows": "audodesk-maya_2014_windows.json",
            },
        }
    },
    {
        name: "Blender",
        data: {
            "v2.70": {
                "mac": "blender_v2.70_mac.json",
                "windows": "blender_v2.70_windows.json",
            },
            "v2.68": {
                "mac": "blender_v2.68_mac.json",
            },
        }
    },
];
