// DO NOT EDIT THIS FILE
// This file is automatically generated when new ApplicationConfigs are serialized
// look in /shmaplib/appdata.py at regenerate_site_apps_js()

var sitedata_apps = [
    {
        name: "Adobe Photoshop",
        data: {
            "v14.2": {
                "windows": "adobe-photoshop_v14.2_windows.json",
                "mac": "adobe-photoshop_v14.2_mac.json",
            },
        }
    },
    {
        name: "Blender",
        data: {
            "v2.68": {
                "mac": "blender_v2.68_mac.json",
            },
            "v2.70": {
                "mac": "blender_v2.70_mac.json",
            },
        }
    },
];
