// DO NOT EDIT THIS FILE
// This file is automatically generated when the FLASK webserver runs
// look in /site/__init__.py at generate_apps_js()

var sitedata_apps = [
    {
        name: "Photoshop",
        data: {
            "v14.2": {
                "mac": "photoshop_v14.2_mac.json",
            },
        }
    },
    {
        name: "Blender",
        data: {
            "2.70": {
                "mac": "blender_2.70_mac.json",
            },
            "2.68": {
                "mac": "blender_2.68_mac.json",
            },
        }
    },
];
